name: Docker

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
    tags:
      - 'v*.*.*'

jobs:

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - name: Prepare
      id: prep
      run: |
        REGCTL_IMAGE=regclient/regctl
        VERSION=noop
        if [ "${{ github.event_name }}" = "schedule" ]; then
          VERSION=nightly
        elif [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        elif [[ $GITHUB_REF == refs/heads/* ]]; then
          VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
            VERSION=edge
          fi
        elif [[ $GITHUB_REF == refs/pull/* ]]; then
          VERSION=pr-${{ github.event.number }}
        fi
        TAGS_SCRATCH="${REGCTL_IMAGE}:${VERSION}"
        TAGS_ALPINE="${REGCTL_IMAGE}:${VERSION}-alpine"
        if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
          MINOR=${VERSION%.*}
          MAJOR=${MINOR%.*}
          TAGS_SCRATCH="${TAGS_SCRATCH},${REGCTL_IMAGE}:${MINOR},${REGCTL_IMAGE}:${MAJOR},${REGCTL_IMAGE}:latest"
          TAGS_ALPINE="${TAGS_ALPINE},${REGCTL_IMAGE}:${MINOR}-alpine,${REGCTL_IMAGE}:${MAJOR}-alpine,${REGCTL_IMAGE}:alpine"
        fi
        echo ::set-output name=version::${VERSION}
        echo ::set-output name=regctl_tags_scratch::${TAGS_SCRATCH}
        echo ::set-output name=regctl_tags_alpine::${TAGS_ALPINE}
        echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

    - name: Check out code
      uses: actions/checkout@v2

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
     
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
     
    - name: Cache docker build
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx

    - name: Build and push scratch
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/Dockerfile.regctl.buildkit
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        push: ${{ github.event_name != 'pull_request' }}
        target: release-scratch
        tags: ${{ steps.prep.outputs.regctl_tags_scratch }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        labels: |
          org.opencontainers.image.created=${{ steps.prep.outputs.created }}
          org.opencontainers.image.source=${{ github.repositoryUrl }}
          org.opencontainers.image.version=${{ steps.prep.outputs.version }}
          org.opencontainers.image.revision=${{ github.sha }}

    - name: Build and push alpine
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/Dockerfile.regctl.buildkit
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        push: ${{ github.event_name != 'pull_request' }}
        target: release-alpine
        tags: ${{ steps.prep.outputs.regctl_tags_alpine }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        labels: |
          org.opencontainers.image.created=${{ steps.prep.outputs.created }}
          org.opencontainers.image.source=${{ github.repositoryUrl }}
          org.opencontainers.image.version=${{ steps.prep.outputs.version }}
          org.opencontainers.image.revision=${{ github.sha }}
